version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pharmazing
    ports:
      - 3010:3010
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
