export enum AppState {
    LOADING = "LOADING",
    FIRST_TIME = "FIRST_TIME",
    RECORDER_OPENED = "RECORDER_OPENED",
    EDITOR_OPENED = "EDITOR_OPENED",
    MOBILE_EDITOR_OPENED = "MOBILE_EDITOR_OPENED",
  }